"""create matches and events tables

Revision ID: 325e8220502f
Revises: c7a8c2c6edef
Create Date: 2026-07-17 12:56:42.880610

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "325e8220502f"
down_revision: str | None = "c7a8c2c6edef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("opponent_name", sa.String(), nullable=True),
        sa.Column("match_date", sa.Date(), nullable=True),
        sa.Column("video_url", sa.String(), nullable=True),
        sa.Column("video_duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("in_progress", "reviewed", "closed", name="match_status"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("pass", "duel", "shot", "set_piece", "defensive_action", name="event_category"),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum(
                "short_pass",
                "long_pass",
                "cross",
                "through_ball",
                "dribble_duel",
                "tackle_duel",
                "aerial_duel",
                "shot_open_play",
                "header_shot",
                "corner_kick",
                "direct_free_kick",
                "indirect_free_kick",
                "penalty_kick",
                "throw_in",
                "interception",
                "clearance",
                "loose_ball_recovery",
                "goalkeeper_save",
                name="event_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.Enum(
                "completed",
                "intercepted",
                "out_of_bounds",
                "blocked",
                "won",
                "lost",
                "foul_committed",
                "foul_received",
                "goal",
                "saved",
                "off_target",
                "post_or_crossbar",
                "blocked_defender",
                "possession_retained",
                "possession_lost",
                "to_corner_or_throw",
                name="event_result",
            ),
            nullable=False,
        ),
        sa.Column("x_start", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("y_start", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("x_end", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("y_end", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("video_timestamp_seconds", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "pressure",
            sa.Enum("under_pressure", "no_pressure", name="pressure_state"),
            nullable=True,
        ),
        sa.Column(
            "body_part", sa.Enum("right_foot", "left_foot", "head", name="body_part"), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    op.drop_table("matches")
    # ### end Alembic commands ###

    # Autogenerate does NOT drop native Postgres ENUM types on downgrade
    # (a known Alembic limitation), which breaks a subsequent upgrade
    # with "type already exists". Drop them explicitly here.
    bind = op.get_bind()
    sa.Enum(name="event_category").drop(bind, checkfirst=True)
    sa.Enum(name="event_type").drop(bind, checkfirst=True)
    sa.Enum(name="event_result").drop(bind, checkfirst=True)
    sa.Enum(name="pressure_state").drop(bind, checkfirst=True)
    sa.Enum(name="body_part").drop(bind, checkfirst=True)
    sa.Enum(name="match_status").drop(bind, checkfirst=True)
