"""add owner_id to teams

Revision ID: 4ba71ffda087
Revises: bb54edd214f5
Create Date: 2026-07-23 08:55:23.421754

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ba71ffda087"
down_revision: str | None = "bb54edd214f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("owner_id", sa.Uuid(), nullable=True))
    op.create_foreign_key("fk_teams_owner_id_users", "teams", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_teams_owner_id_users", "teams", type_="foreignkey")
    op.drop_column("teams", "owner_id")
    # ### end Alembic commands ###
